library(tidyverse)
library(wid)
#--------------------------------------------------------------------------------------
mega_WID_df <- download_wid(
  indicators = c('mcfcco', 'mcfcnf', 'mcwbus',
                 'mcwdeb', 'mnsrco', 'mgdpro',
                 'mnwbus', 'mcomhn', 'mssbgo',
                 'mssbco', 'mconfc', 'msopgo',
                 'mspigo', 'mprinf', 'mprgnf',
                 'mgsrnf', 'mnsrnf', 'mtaxnf',
                 'inyixx', 'mprifc', 'mpwbus',
                 'mpinnx', 'mfkpin', 'mprpgo',
                 'mprpnf', 'mprpco', 'mprico',
                 'mprpho', 'mpriho', 'mcomnp',
                 'mprpnp', 'mcfcho', 'mgwbus',
                 'mnmxho', 'mptxgo', 'mcfchn',
                 'mcfcgo', 'mnninc', 'mprigo',
                 'mprpfc', 'mgsrfc', 'mprgfc',
                 'mtaxfc', 'mcwfin', 'mnsrfc',
                 'mpwfin', 'mgwfin', 'npopul',
                 'npopem', 'xlcusx', 'xlcusp',
                 'wlabsh', 'wcapsh', 'wwealn',
                 'wwealp', 'wwealh', 'wwealc',
                 'wwealg', 'mnwnfa', 'mtaxco',
                 'mgwnfa', 'mssbhn', 'mcwnfa',
                 'mnsrgo', 'mnsrhn', 'mnsrco',
                 'mnwdwe', 'mnwlan', 'mnwagr',
                 'mnwnat', 'mnwodk', 'mfdirx',
                 'mfsubx', 'mprggo', 'mgwagr',
                 "mgwnat", "mgwhou", 'mcongo',
                 'mgpsgo', 'mdefgo', 'mecogo',
                 'mhougo', 'mheago', 'medugo',
                 'msopgo', 'mprihn', 'mprphn',
                 'mnwhou', 'mcongo', 'mgpsgo',
                 'mecogo', 'mhougo', 'mheago',
                 'medugo', 'msopgo', "mgwdeb",
                 'mdefgo', 'mgwodk', 'mpwodk',
                 'mhwodk', 'miwodk', 'mcwodk'),
  areas = c("AU", "AT", "BE", "CA", "CL",
            "CZ", "FR", "DE", "EE", "ES",
            'FI', "FR", "GB", "GR", "HU",
            'IE', "IL", "IS", "IT", "JP",
            "KR", "LU", "MX", "NL", "NZ",
            "NO", "PL", "PT", "SK", "SI",
            "SE", "CH", "TR", "US"),
  years = 1960:2022,
  ages = 999,
  perc = "all") %>%
  select(-percentile) %>%
  pivot_wider(names_from = variable, values_from = value) %>%
  rename(iso2 = country,
         GDP_2021_LCU = mgdpro999i,
         population_employed_total = npopem999i,
         population_total_male = npopul999m,
         population_total_female = npopul999f,
         population_total = npopul999i,
         market_exchange_rate_LCU_per_USD = xlcusx999i,
         ppp_convesion_rate_LCU_per_USD = xlcusp999i,
         national_income_price_index = inyixx999i,
         ratio_labor_share_factor_price_national_income = wlabsh999i,
         ratio_capital_share_factor_price_national_income = wcapsh999i,
         ratio_net_national_wealth_to_net_national_income = wwealn999i,
         ratio_net_priavte_wealth_to_net_national_income = wwealp999i,
         ratio_net_personal_wealth_to_net_national_income = wwealh999i,
         ratio_net_public_wealth_to_net_national_income = wwealg999i,
         national_compensation_employees_total_2021_LCU = mcomhn999i,
         national_consumption_fixed_capital_2021_LCU = mconfc999i,
         national_net_income_2021_LCU = mnninc999i,
         national_housing_assets_2021_LCU = mnwhou999i,
         national_agricultural_land_2021_LCU = mnwagr999i,
         national_dwellings_2021_LCU = mnwdwe999i,
         national_land_under_dwellings_2021_LCU = mnwlan999i,
         national_natural_capital_2021_LCU = mnwnat999i,
         national_machinery_plus_equip_2021_LCU = mnwodk999i,
         national_FDI_recieved_2021_LCU = mfdirx999i,
         national_foreign_subsidies_production_2021_LCU = mfsubx999i,
         national_nonfinancial_assets_2021_LCU = mnwnfa999i,
         national_taxes_products_production_2021_LCU = mptxgo999i,
         national_taxes_less_subsidies_production_imports_2021_LCU = mptxgo999i,
         national_net_foreign_capital_income_2021_LCU = mpinnx999i,
         national_net_capital_income_2021_LCU = mfkpin999i,
         national_business_assets_2021_LCU = mnwbus999i,
         private_business_assets_2021_LCU_current_ppp = mpwbus999i,
         corporate_business_assets_2021_LCU = mcwbus999i,
         corporate_consumption_fixed_capital_2021_LCU = mcfcco999i,
         corporate_tax_2021_LCU = mtaxco999i,
         corporate_nonfinancial_assets_2021_LCU = mcwnfa999i,
         corporate_net_operating_surplus_2021_LCU = mnsrco999i,
         corporate_debt_2021_LCU = mcwdeb999i,
         corporate_net_primary_income_2021_LCU = mprico999i,
         corporate_net_property_income_2021_LCU = mprpco999i,
         corporate_machinery_plus_equip_2021_LCU = mcwodk999i,
         corporate_financial_assets_2021_LCU = mcwfin999i,
         nonfinancial_corps_corporate_tax_2021_LCU = mtaxnf999i,
         nonfinancial_corps_net_property_income_2021_LCU = mprpnf999i,
         nonfinancial_corp_net_primary_income_2021_LCU = mprinf999i,
         nonfinancial_corp_gross_operating_surplus_2021_LCU = mgsrnf999i,
         nonfinancial_corps_net_operating_surplus_2021_LCU = mnsrnf999i,
         nonfinancial_corps_gross_primary_income_2021_LCU = mprgnf999i,
         nonfinancial_corp_consumption_fixed_capital_2021_LCU = mcfcnf999i,
         nonfinancial_corps_net_operating_surplus_2021_LCU = mnsrnf999i,
         financial_corp_net_primary_income_2021_LCU = mprifc999i,
         financial_corps_gross_operating_surplus_2021_LCU = mgsrfc999i,
         financial_corps_net_operating_surplus_2021_LCU = mnsrfc999i,
         financial_corps_gross_primary_income_2021_LCU = mprgfc999i,
         financial_corps_net_property_income_2021_LCU = mprpfc999i,
         financial_corps_paid_corporate_taxes_2021_LCU = mtaxfc999i,
         financial_corps_consumption_fixed_capital_2021_LCU = mcfcnf999i,
         financial_corps_net_operating_surplus_2021_LCU = mnsrfc999i,
         household_net_primary_income_2021_LCU = mpriho999i,
         household_machinery_plus_equip_2021_LCU = mhwodk999i,
         household_net_property_income_2021_LCU = mprpho999i,
         household_net_mixed_income_2021_LCU = mnmxho999i,
         household_consumption_fixed_capital_2021_LCU = mcfcho999i,
         NPISH_plus_household_machinery_plus_equip_2021_LCU = mpwodk999i,
         NPISH_net_property_income_2021_LCU = mprpnp999i,
         NPISH_households_consumption_fixed_capital_2021_LCU = mcfchn999i,
         NPISH_households_net_primary_income_2021_LCU = mprihn999i,
         NPISH_households_property_income_2021_LCU = mprphn999i,
         NPISH_compensation_employees_2021_LCU = mcomnp999i,
         NPISH_household_financial_assets_2021_LCU = mpwfin999i,
         NPISH_machinery_plus_equip_2021_LCU = miwodk999i,
         NPISH_housholds_net_operating_surplus_2021_LCU = mnsrhn999i,
         govt_gross_primary_income_2021_LCU = mprggo999i,
         govt_housing_assets_2021_LCU = mgwhou999i,
         govt_agricultural_land_2021_LCU = mgwagr999i,
         govt_natural_capital_2021_LCU = mgwnat999i,
         govt_nonfinancial_assets_2021_LCU = mgwnfa999i,
         govt_financial_assets_2021_LCU = mgwfin999i,
         govt_net_operating_surplus_2021_LCU = mnsrgo999i,
         govt_net_primary_income_2021_LCU = mprigo999i,
         govt_business_nonfinancial_assets_2021_LCU = mgwbus999i,
         govt_consumption_fixed_capital_2021_LCU = mcfcgo999i,
         govt_social_protection_spending_2021_LCU = msopgo999i,
         govt_subsidies_production_imports_2021_LCU = mspigo999i,
         govt_private_social_insurance_2021_LCU = mssbco999i,
         govt_public_social_insurance_2021_LCU = mssbgo999i,
         govt_total_expenditure_2021_LCU = mcongo999i,
         govt_defense_expenditure_2021_LCU = mdefgo999i,
         govt_econ_affairs_expenditure_2021_LCU = mecogo999i,
         govt_education_expenditure_2021_LCU = medugo999i,
         govt_misc_public_services_2021_LCU = mgpsgo999i,
         govt_health_spending_2021_LCU = mheago999i,
         govt_housing_spending_2021_LCU = mhougo999i,
         govt_debt_2021_LCU = mgwdeb999i,
         govt_machinery_plus_equip_2021_LCU = mgwodk999i)
#---------------------------------------------------------------------------------------
wid_inequality_df <- download_wid(
  indicators = 'sptinc',
  areas = c("AU", "AT", "BE", "CA", "CL",
            "CZ", "FR", "DE", "EE", "ES",
            'FI', "FR", "GB", "GR", "HU",
            'IE', "IL", "IS", "IT", "JP",
            "KR", "LU", "MX", "NL", "NZ",
            "NO", "PL", "PT", "SK", "SI",
            "SE", "CH", "TR", "US"),
  years = 1960:2022,
  ages = 992,
  perc = c('p90p100', 'p99p100', 'p99.9p100',
           'p0p20', 'p0p25', 'p0p30', 'p0p50', 'p0p99', 'p0p90', 'p0p99.9',
           'p10p11', 'p20p21', 'p25p26','p30p31', 'p50p51', 'p90p91'),
  pop = 'j') %>%
  pivot_wider(names_from = c(variable, percentile), values_from = value) %>%
  arrange(country, year) %>%
  rename(iso2 = country,
         pre_tax_income_share_bottom_20pct = sptinc992j_p0p20,
         pre_tax_income_share_bottom_25pct = sptinc992j_p0p25,
         pre_tax_income_share_bottom_30pct = sptinc992j_p0p30,
         pre_tax_income_share_bottom_50pct = sptinc992j_p0p50,
         pre_tax_income_share_bottom_90pct = sptinc992j_p0p90,
         pre_tax_income_share_bottom_99pct = sptinc992j_p0p99,
         pre_tax_income_share_top_10pct = sptinc992j_p90p100,
         pre_tax_income_share_top_0.1pct = sptinc992j_p99.9p100,
         pre_tax_income_share_top_1pct = sptinc992j_p99p100,
         pre_tax_income_share_10th_pctile = sptinc992j_p10p11,
         pre_tax_income_share_20th_pctile = sptinc992j_p20p21,
         pre_tax_income_share_25th_pctile = sptinc992j_p25p26,
         pre_tax_income_share_30th_pctile = sptinc992j_p30p31,
         pre_tax_income_share_50th_pctile = sptinc992j_p50p51,
         pre_tax_income_share_90th_pctile = sptinc992j_p90p91)
#---------------------------------------------------------------------------------------
wid_pt_disp_income_df <- download_wid(
  indicators = c('aptinc'),
  areas = c("AU", "AT", "BE", "CA", "CL",
            "CZ", "FR", "DE", "EE", "ES",
            'FI', "FR", "GB", "GR", "HU",
            'IE', "IL", "IS", "IT", "JP",
            "KR", "LU", "MX", "NL", "NZ",
            "NO", "PL", "PT", "SK", "SI",
            "SE", "CH", "TR", "US"),
  years = 1960:2022,
  ages = 992,
  pop = 'j',
  perc = c('p20p21',
           'p30p31',
           'p50p51',
           'p80p81',
           'p90p91',
           'p99p100')) %>%
  pivot_wider(names_from = c(variable, percentile), values_from = value) %>%
  arrange(country, year) %>%
  rename(iso2 = country,
         avg_pre_tax_disp_income_20th_pctile_2021_LCU = aptinc992j_p20p21,
         avg_pre_tax_disp_income_30th_pctile_2021_LCU = aptinc992j_p30p31,
         avg_pre_tax_disp_income_50th_pctile_2021_LCU = aptinc992j_p50p51,
         avg_pre_tax_disp_income_80th_pctile_2021_LCU = aptinc992j_p80p81,
         avg_pre_tax_disp_income_90th_pctile_2021_LCU = aptinc992j_p90p91,
         avg_pre_tax_disp_income_99th_pctile_2021_LCU = aptinc992j_p99p100)
#---------------------------------------------------------------------------------------
wid_gini_df <- download_wid(
  indicators = c('gptinc'),
  areas = c("AU", "AT", "BE", "CA", "CL",
            "CZ", "FR", "DE", "EE", "ES",
            'FI', "FR", "GB", "GR", "HU",
            'IE', "IL", "IS", "IT", "JP",
            "KR", "LU", "MX", "NL", "NZ",
            "NO", "PL", "PT", "SK", "SI",
            "SE", "CH", "TR", "US"),
  years = 1960:2022,
  ages = 992,
  pop = c("j"),
  perc = "p0p100") %>%
  select(-percentile) %>%
  pivot_wider(names_from = variable, values_from = value) %>%
  rename(iso2 = country,
         gini_coeff = gptinc992j) %>%
  arrange(iso2, year)
#---------------------------------------------------------------------------------------
wid_df_final <- mega_WID_df %>%
  left_join(wid_inequality_df, by = c('iso2', 'year')) %>%
  left_join(wid_pt_disp_income_df, by = c('iso2', 'year')) %>%
  left_join(wid_gini_df, by = c('iso2', 'year')) %>%
  select('iso2', 'year', 'market_exchange_rate_LCU_per_USD', 'ppp_convesion_rate_LCU_per_USD', 'national_income_price_index',
         sort(colnames(.))) %>%
  rename_with( ~ paste("wid", .x, sep = "_")) %>%
  rename(iso2 = wid_iso2,
         year = wid_year)
#---------------------------------------------------------------------------------------
write_rds(wid_df_final, "~/Google Drive/My Drive/3 - Misc. Data Research/Fed Data/wid_df_final.rds")
#---------------------------------------------------------------------------------------
